server:
  port: 8081


spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: processos
  datasource:
    url: jdbc:h2:mem:processos
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true


  # swagger-ui custom path
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"